Project CoVID69{
database_type: 'MySQL'
note: '''
# CoVID69
### A CoVID-19 case tracker.

This is a University Project. CoVID69 is a set of tools that track CoVID-19 cases. It helps its users make informed choices about their commute based on data collected by its community. Furthermore, it notifies people that may have been exposed to the virus.

You can see more information about this project here : https://github.com/iloudaros/CoVID69'''
}

Table User
{
username varchar [pk]
password varchar
email varchar
is_manager bit [default: 0]
note: 'The table where user information and their role is stored'
}

Table POI
{
  id varchar [pk]
  name varchar
  address varchar
  lat float
  lng float
  rating float4 [default: 0]
  rating_n int [default: 0]
note:'This information is collected using this library: https://github.com/m-wrzr/populartimes'

}

Table Types
{
  poi varchar [ref: > POI.id]
  type varchar

  indexes{
  (poi,type) [pk]
  }

  note: 'We use this table to store the types of each Point of Interest'
}

Table PopularTimes
{
  poi varchar [ref: > POI.id]
  day day
  time int
  data int [default: 0]

  indexes{
    (poi,day,time) [pk]
  }
  note: 'The data for the popular times as given by the Google API'
}

Table UserVisits
{
  user varchar [ref: > User.username]
  poi varchar [ref: > POI.id]
  timestamp datetime [default: `NOW()`]
  report int
note: 'Here we store the reported visits of the user, as well as the reported number of people present'
}

Table Cases
{
  user varchar [pk, ref: - User.username]
  date date
note: 'Here we store the user reported cases of CoVID19'
}
