Project Covid_69{
database_type: 'MySQL'
note: 'This is a university Project. Covid-69 is a set of tools that track covid-19 cases. It helps its users make informed choices about their commute based on data collected by its community. Furthermore, it notifies people that may have been exposed to the virus'
}

Table User
{
username varchar [pk]
password varchar
email varchar
is_manager bit
}

Table POI
{
  id varchar [pk]
  name varchar
  address varchar
  lat float
  lng float
  rating float4
  rating_n int

}

Table Types
{
  poi varchar [ref: > POI.id]
  type varchar

  indexes{
  (poi,type) [pk]
  }
}

Table PopularTimes
{
  poi varchar [ref: > POI.id]
  day day
  time int
  data int

  indexes{
    (poi,day,time) [pk]
  }
}

Table UserVisits
{
  user varchar [ref: > User.username]
  poi varchar [ref: > POI.id]
  timestamp datetime [default: 'NOW()']
  report int

}

Table Cases
{
  user varchar [pk, ref: - User.username]
  date date

}
